plugins {
    id 'com.android.application'
}

android {
    namespace 'com.yake.ttsserver'
    compileSdk 34

    defaultConfig {
        applicationId "com.yake.ttsserver"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            // 自用工具，直接用 debug 签名，方便 adb install 覆盖安装
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
